name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install poetry-book-cli
      run: cargo install poetry-book-cli
    - name: Run poetry-book-cli
      run: |
        examples=(*/)
        mkdir deploy
        for dir in $examples; do
          mkdir deploy/$dir
          poetry-book-cli $dir
          mv $dir/out/*.tex deploy/$dir
        done
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./deploy
      with:
        emptyCommits: false
